// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for Prisma CLI operations (migrations, db push, etc.)
    // Pooled connections (DATABASE_URL) don't work for schema modifications
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
